log_level: DEBUG

# How often should app check if the IP was updated in minutes.
check_interval_in_minutes: 5

# Use this alternative format for more helpful dev logging:
# [%(asctime)s] %(levelname)s:%(name)s [%(funcName)s:%(lineno)d] %(message)s
log_format: "%(levelname)s:%(name)s:%(message)s"
log_datefmt: '%Y-%m-%dT%H:%M:%S'

# Applies to both connect & read portions of the request, so this means each
# request could potentially take up to double the value specified here.
requests_timeout_seconds: 5
getreq_retry_limit: 5

# WAN IP API URL
wan_ip_endpoints:
  - 'https://api.seeip.org'
  - 'https://api.ipify.org'
  - 'https://ifconfig.me/ip'

# GitHub Gist section
# To enable public IP gist publishing change 'enabled' flag to true
# Please note that existing gist ID must be provided in <GIST_ID>
# <GITHUB_API_TOKEN> is also required to be changed to a proper token
github_gist:
  enabled: false
  gists_url: 'https://api.github.com/gists'
  gist_id: '<GIST_ID>'
  api_token: '<GITHUB_API_TOKEN>'
  requests_timeout_seconds: 3
  retry_limit: 5

# DNS provider apis.
dns_apis:
  NAME_COM:
    # name.com API
    api_host: 'api.name.com'
    username: 'whatever@example.com'
    token: 'YOUR_TOKEN'
    domain_name: 'example.com'
    # domain_id can be found by manually querying name.com's listrecords domain API
    # or by viewing the html source in your browser on the URL:
    # https://www.name.com/account/domain/details/{DOMAIN}#dns
    # The ID will be mentioned on a checkbox for the row you want, prefixed with
    # some letters which you should remove in this config since the ID is only
    # numeric.
    domain_id: 123456
